### ISSUE TITLE
missing graphics when hosting on github pages

### ISSUE THREAD

**Issue by liz-miller** [devcows/hugo-universal-theme#44] opened 2017-02-09 00:00 UTC
I can't seem to get this theme to work completely when hosting on github pages. Some of my pictures, graphics, etc are missing. This issue doesn't happen when I run hugo locally on my computer. Any thoughts on how to correct this?

**Comment by adrianmo** [comment] 2017-02-09 09:00
Hi @liz-miller, it looks like there something misconfigured or the static files directory is not being uploaded correctly.

Please make sure the [`baseUrl`](https://github.com/devcows/hugo-universal-theme/blob/master/exampleSite/config.toml#L1) setting in your config.toml file is configured correctly. 

It would also be useful if you could provide a link to your repo to debug the issue.

Best,
-Adrián

**Comment by liz-miller** [comment] 2017-02-09 13:29
Yes, something is funky about the site generation when hosting on github. I was able to get a few images to load from /static/img (logos seem to work), and others I have to reference directly using the online image source URL (images of people). 

My repository is at https://github.com/learnroboticsclass/learnroboticsclass.github.io

None of my source files are there, just the files generated from running Hugo locally on my computer. 

Thanks!

**Comment by adrianmo** [comment] 2017-02-09 16:29
I don't know if you made any change, but it looks good to me and all pictures are being displayed correctly. If you are still having problems try to clean the cache or using another browser.

Good luck with the robotics class ;)

**Comment by liz-miller** [comment] 2017-02-16 14:38
Yes, so what i had to do is "copy image address" of the images that are in my static/img and use those URL's directly. What I'd like tot be able to do is reference /static/img/<img name> inside the markdown or config files rather than having to push to github and get an image address. 

& Thank you! It's an exciting new venture :)

**Comment by schuster-rainer** [comment] 2017-03-08 20:39
I guess it is an issue of http vs. https. 

Make sure to use the relative url 

baseUrl  = "//learnrobotics.org"

if you want to link to to an image than all you have to do is use: ![This is an image](/img/image.png)
where the actual file is /static/img/image.png

**Comment by Simnol** [comment] 2017-03-18 22:06
Seeing the same issue with http/https, I also note that if I go to Liz's site on https (apart from the cert error, which I'm guessing was there for testing) the formatting is garbled.

**Comment by adrianmo** [comment] 2017-03-20 11:29
@Simnol and @liz-miller: the webserver is able to serve the website via HTTPS but the assets (i.e. css, images, js) are fetched via HTTP as configured in your config.toml, causing your browser to block the request and, therefore, ruining the formatting.

![](http://oi66.tinypic.com/u9ekh.jpg)

As @schuster-rainer said, it's a problem with your `baseUrl` setting in your config.toml. Remove the protocol as @schuster-rainer suggested above and let us know how it goes.

```
baseUrl  = "//learnrobotics.org"
```

**Comment by Simnol** [comment] 2017-03-20 12:45
Hi @adrianmo,

I actually think the issue isn't protocol-specifying, rather it seems to be a trailing slash on the URL that's required.
So not:
```
baseUrl  = "//learnrobotics.org"
```
But rather:
```
baseUrl  = "//learnrobotics.org/"
```
I had a look at the generated site and noticed melding of url and subsequent page URLs.

Hope that helps someone else, fixed the issue for me.

**Comment by adrianmo** [comment] 2017-03-20 13:11
Hi @Simnol,

You are right about the trailing slash. That can also cause problems if it's not appended. But the protocol is definitely causing issues if the site is served via HTTPS and some assets not. 

I will close the issue, but feel free to reopen it if somebody is still experiencing this.

**Closed by adrianmo** 2017-03-20 13:11 UTC
